### ISSUE TITLE
Error Compiling After Updating to Espressif 4.1.0

### ISSUE THREAD

**Issue by Alaa-Aim** [vortigont/espem#19]
@vortigont , I updated the Espressif 3.5.2 to 4.1.0 , after updating I get this error in compiling as shown below :

.pio/libdeps/espem/LITTLEFS/src/LittleFS.cpp: In member function 'virtual bool LITTLEFSImpl::exists(const char*)':
.pio/libdeps/espem/LITTLEFS/src/LittleFS.cpp:44:28: error: no matching function for call to 'LITTLEFSImpl::open(const char*&, const char [2])'
     File f = open(path, "r");
                            ^
In file included from .pio/libdeps/espem/LITTLEFS/src/LittleFS.cpp:17:
C:/Users/ALAA/.platformio/packages/framework-arduinoespressif32/libraries/FS/src/vfs_api.h:38:17: note: candidate: 'virtual fs::FileImplPtr VFSImpl::open(const char*, const char*, bool)'
     FileImplPtr open(const char* path, const char* mode, const bool create) override;
                 ^~~~
C:/Users/ALAA/.platformio/packages/framework-arduinoespressif32/libraries/FS/src/vfs_api.h:38:17: note:   candidate expects 3 arguments, 2 provided 
*** [.pio\build\espem\lib2f9\LITTLEFS\LITTLEFS.cpp.o] Error 1
.pio/libdeps/espem/EmbUI/EmbUI/EmbUI.cpp: In member function 'void EmbUI::begin()':
.pio/libdeps/espem/EmbUI/EmbUI/EmbUI.cpp:130:12: error: 'LittleFS' was not declared in this scope
     while(!LittleFS.begin(FORMAT_LITTLEFS_IF_FAILED)){
            ^~~~~~~~
.pio/libdeps/espem/EmbUI/EmbUI/EmbUI.cpp:130:12: note: suggested alternative: 'bitClear'
     while(!LittleFS.begin(FORMAT_LITTLEFS_IF_FAILED)){
            ^~~~~~~~
            bitClear
.pio/libdeps/espem/EmbUI/EmbUI/config.cpp: In member function 'void EmbUI::save(const char*, bool)':
.pio/libdeps/espem/EmbUI/EmbUI/config.cpp:19:9: error: 'LittleFS' was not declared in this scope
         LittleFS.rename(FPSTR(P_cfgfile),FPSTR(P_cfgfile_bkp));
         ^~~~~~~~
.pio/libdeps/espem/EmbUI/EmbUI/config.cpp:19:9: note: suggested alternative: 'bitClear'
         LittleFS.rename(FPSTR(P_cfgfile),FPSTR(P_cfgfile_bkp));
         ^~~~~~~~
         bitClear
.pio/libdeps/espem/EmbUI/EmbUI/config.cpp:23:22: error: 'LittleFS' was not declared in this scope
         configFile = LittleFS.open(_cfg, "w"); // PSTR("w") использовать нельзя, будет исключение!
                      ^~~~~~~~
.pio/libdeps/espem/EmbUI/EmbUI/config.cpp:23:22: note: suggested alternative: 'bitClear'
         configFile = LittleFS.open(_cfg, "w"); // PSTR("w") использовать нельзя, будет исключение!
                      ^~~~~~~~
                      bitClear
.pio/libdeps/espem/EmbUI/EmbUI/config.cpp: In member function 'bool EmbUI::loadjson(const char*, ArduinoJson6194_F1::DynamicJsonDocument&)':        
.pio/libdeps/espem/EmbUI/EmbUI/config.cpp:64:21: error: 'LittleFS' was not declared in this scope
     File jsonFile = LittleFS.open(filepath, "r");
                     ^~~~~~~~
.pio/libdeps/espem/EmbUI/EmbUI/config.cpp:64:21: note: suggested alternative: 'bitClear'
     File jsonFile = LittleFS.open(filepath, "r");
                     ^~~~~~~~
                     bitClear
*** [.pio\build\espem\libf25\EmbUI\config.cpp.o] Error 1
*** [.pio\build\espem\libf25\EmbUI\EmbUI.cpp.o] Error 1
=========================================================== [FAILED] Took 23.02 seconds ===========================================================

Environment    Status    Duration
-------------  --------  ------------
espem          FAILED    00:00:23.020
====================================================== 1 failed, 0 succeeded in 00:00:23.020 ======================================================

the main error are in LITTELFS library as shown in screen shoot
![image](https://user-images.githubusercontent.com/64470118/164640315-102e07a8-5654-49c6-a526-3096a47daadf.png)

**Comment by vortigont** [comment]
every update bring some mess. Fixed in upstream 4520447
