### ISSUE TITLE
Can not import database with phpMyAdmin

### ISSUE THREAD

**Issue by langtupt** [vortigont/espem#2]
Dear Vortigont,
Could you please help me check the database ,i import **pzmysqlstat.sql** in phpmyadmin and do not working.
Please help see the picture below can you help me fix?
Thank you very much
http://prntscr.com/gffkte

**Comment by vortigont** [comment]
@langtupt 
You should import only [pzem_mysql.sql](https://github.com/vortigont/espem/blob/master/sql/pzem_mysql.sql) file. it contains all needed db structs. 
**pzmysqlstat.sql** is only reference queries, not used directly anywhere.

**Comment by langtupt** [comment]
Dear Vortigont,
Please see the picture problem below. i import pzem_mysql.sql and do not working.
http://prntscr.com/gldelt
please advice and help me fix.

Thank you very much

**Comment by vortigont** [comment]
I'm not sure what are you trying to do. Your screen shows that you are already attached to DB 'huuxuanc'.
But 'pzem_mysql.sql' tries to create new DB 'pzem', that's why you get this permission error. If you are not allowed to create new DB's - than remove 'CREATE DATABASE...' and "USE `pzem`;" statements from 'pzem_mysql.sql' and create only tables within your current DB.

**Comment by IgorVinokur** [comment]
Dear Vortigont,
Where I can find detailed instruction of the configuration? 

Thanks in Advance

**Comment by vortigont** [comment]
@IgorVinokur so sorry, I was to lazy to write the complete guide. But if you have any questions, pls ask, I'll try to help you.

**Comment by smah1980** [comment]
@vortigont hello, I am not able to get the view of index.php, I have installed cacti as well as smarty template engine. also set the db parameters in the config.php. Still getting 500 error :(
could you please help where I am doing wrong.

**Comment by vortigont** [comment]
Hello @smah1980, pls check your webserver's error log file, it must show what caused the error.
You may also set ini_set('display_errors', 1); in the config.php. But error 500 usually means that cgi execution failed at the early stage, for e.x. missing php module, file access error or something like this.

**Comment by smah1980** [comment]
Thanks @vortigont its working now, it was permission issue, I just fixed that, now will check with the meter by tomorrow.
Thanks alot (Y)

**Comment by vortigont** [comment]
@smah1980 sorry, was out of office for a while :) just in case if you still heed help on this?
