### ISSUE TITLE
SyntaxError: JSON.parse

### ISSUE THREAD

**Issue by Alaa-Aim** [vortigont/espem#25]
@vortigont, when trying access "http://espem/fw", I get this error 
"SyntaxError: JSON.parse: end of data when property name was expected at line 1 column 200 of the JSON data"

**Comment by vortigont** [comment]
Hello @Alaa-Aim,
unfortunately I do not have a working PZEM at hand now. Can you post here a json reply? Might be some comma or bracket missing.

**Comment by Alaa-Aim** [comment]
@vortigont , I've tried to look for this error in the webpage files, no luck, could please point me to the file responsible of this error 

![image](https://user-images.githubusercontent.com/64470118/190625515-65790429-c2a0-4d75-88fa-514e85c71d18.png)

**Comment by vortigont** [comment]
it's a browser's error. Just click on a 'raw' tab to see json body

**Comment by Alaa-Aim** [comment]
Tried different browser and no error , thanks
