### ISSUE TITLE
ESP32 S2 Mini, No WiFi

### ISSUE THREAD

**Issue by Alaa-Aim** [vortigont/espem#27]
@vortigont After compiling for ESP3S2, ESP32-S2FN4R2, the compile & upload everything successful but no AP to configure & Connect to WiFi , below screenshot for board config in *.ini file, Please advise 

![image](https://user-images.githubusercontent.com/64470118/200169116-90a6b8af-162f-41e1-94b3-b33c66eea6da.png)

**Comment by vortigont** [comment]
Hi @Alaa-Aim 
for this to check I need debug output. Pls check `espem_debug` env in the .ini file. Is that a blank new board that you used?

**Comment by Alaa-Aim** [comment]
Hi @vortigont, I've tried this method, but nothing on the serial monitor, this board uses native use not UART, debug section in the *.ini file as below, 
![image](https://user-images.githubusercontent.com/64470118/200263023-cdb07aa6-8c59-4f67-a532-a14d4a1cdc99.png)
the board is brand new and blank, I check it by using it as WiFi AP and it works.

**Comment by Alaa-Aim** [comment]
This is the board i use

![image](https://user-images.githubusercontent.com/64470118/200266075-f3b5c58b-5f3b-43bb-ac80-be8b57a6ffcf.png)

**Comment by vortigont** [comment]
I do not have such boards without serial to test. It may require enabling CDC serial driver.
I'll try to find how to test it when time permits.
Meanwhile I can suggest a feasible workaround - you can upload filesystem image with config file to force enabling AP mode. Put a `config.json` file into `data` dir with a content like this
```
{"APonly":true}```
 Than access AP and configure via GUI as usual

**Comment by Alaa-Aim** [comment]
Hi @vortigont , Unfortunately, didn't work, I'll try use UART, I'll let know the outcome.

**Comment by Alaa-Aim** [comment]
> you may also need to specify `board = lolin_s2_mini` [lolin_s2_mini.json](https://github.com/platformio/platform-espressif32/blob/master/boards/lolin_s2_mini.json) [S2 mini](https://www.wemos.cc/en/latest/s2/s2_mini.html)

Hi @vortigont , Changing the board to lolin_s2_mini , works , many thanks
