### ISSUE TITLE
could you do Video example of this

### ISSUE THREAD

**Issue by juavinas** [vortigont/espem#7]
Hello,
 
  could you do Video regarding this.

**Comment by vortigont** [comment]
Hi @juavinas Unfortunately have no time right now to create demos. Actually this project of mine is quite old although I'm still using it as my main power meter and analyser. I was thinking about full code refactoring when time permits. But cat still ask questions if any, I'll try to help.

**Comment by juavinas** [comment]
Thank you for the answer.

First question you with Arduino compiling espem library to esp8266?

When I compiling I get error with http.h file: const char PROGMEM PGver[] = PMeterESP_VER;

I doing the same, but with 3 phases. Want to run your project first with one Phase, later add 2 more.

**Comment by vortigont** [comment]
First you must copy/rename file config.h.distrib under name config.h and change some default settings of required. The const PMeterESP_VER is defined there with a firmware version

**Comment by juavinas** [comment]
Thank you, will try at home.

**Comment by juavinas** [comment]
Thank you, for help it passes more.

Now another question. You connecting Raspberry pi to esp8266 or how you did it? Because I have server QNAP with mysql in 192.168.1.5 port.

**Comment by juavinas** [comment]
Hello tying to run your webpage: & have question regarding:
// basepath
define('DOC_ROOT', '/var/www/pmeter');
define('SMARTY_DIR', DOC_ROOT . '/smarty/libs/');

what is that & where it needed to link?

**Comment by vortigont** [comment]
It's the path to the content of www dir of this repo. Smarty is an  ancient php templater, pls download it and unpack somewhere.
currently I'm out of reach, will help you later if required

**Comment by vortigont** [comment]
> Thank you, for help it passes more.
> 
> Now another question. You connecting Raspberry pi to esp8266 or how you did it? Because I have server QNAP with mysql in 192.168.1.5 port.

I'm using php/web server on raspberry to poll esp-pzem and store data to sqlite db

**Comment by juavinas** [comment]
I don't understand why these needed, they are from config.php:
 // Default powermeter address/hostname
$default_meter = 'esp-pzem01';

# Default powermeter hostname/ip-address
$meterhost = 'esp-pzem01';

don't you taking data directly from mysql?

Could you find my skype: juavinas. We can directly to talk.
